### PR TITLE
Push travis-fix change to master

### PR DESCRIPTION
**Pull request by edmBernard**
hope it will pass travis

### CODE REVIEW

**Comment by edmBernard** [comment]
sometime libev-dev is found sometime not.

**Comment by edmBernard** [comment]
This time libev-dev can't be found. 
but It don't seem this patch don't fix correctly the issues.
It only silent problem with coverage

**Comment by edmBernard** [comment]
This time I fix correctly fix coverage

**Comment by defnull** [comment]
Thanks for your work. As you can see, it took me a couple of tries to get a clean and reliable build, but its working now :)

**Comment by edmBernard** [comment]
I'm glad to hear my change help you. That was a bit chaotic ^^.

**Pull request closed without merging**
