### PR TITLE
Fixes #772

### LINKED ISSUE #772: Ability to load config from module
Currently it is not possible to load config from a Python module (similar to the way Django does it).

I'd like to propose the following;

```py
class ConfigDict(dict):
    def load_module(self, module_path):
        """
        Load configuration from module path

        >>> load_module('settings.prod')
        """
        assert isinstance(module_path, str)
        config = importlib.import_module(module_path)
        obj = {key: getattr(config, key) for key in dir(config) if key.isupper()}
        self.update(obj)
```

Happy to put together a tested PR if this proposal is accepted

### PR DESCRIPTION
**Pull request by foxx**
Fixes #772, Includes tests, passed.

### CODE REVIEW

**Comment by samstav** [comment]
+1 for Lol in commit messages. Also, nice workaround on dict comprehensions.

LGTM

**Comment by avelino** [comment]
+1
LGTM

**Comment by defnull** [comment]
How about using the bottle.load() function (or its internals) for importing stuff? Thay way you could also load config from a dict in a module (e.g. `myapp.config:conf`) or even from the return value of a function (e.g. `myapp.config:make_config()`).

Also, docs. But that's for later. I'll just merge and we see where we go from here.

**Comment by foxx** [comment]
Ohh, I didn't know about `bottle.load()`, that would be a lot nicer for sure. I'll reopen #772 for improvements. Thanks for the merge/feedback!

**Pull request merged**
