### PR TITLE
Added certfile option to WSGIRefServer to specify SSL

### PR DESCRIPTION
**Pull request by mfm24**
Changes to allow the use of SSL with WSGIRefServer by specifying a certificate file using the 'certfile' key in options.

Based on the example [here](http://www.piware.de/2011/01/creating-an-https-server-in-python/) and my blog post [here](http://www.socouldanyone.com/2014/01/bottle-with-ssl.html). The file specified should be in PEM format containing both private and public keys (it should be possible to add a separate private key too, but this is how I've been using it so far).

### CODE REVIEW

**Comment by kromkrom** [comment]
It's a pity this pull request still isn't merged. SSL with default server allows using Bottle in testing to quickly create fully fledged service emulators.

**Comment by samstav** [comment]
See https://github.com/bottlepy/bottle/pull/647#issuecomment-60152870

**Comment by mfm24** [comment]
Thanks samstav, I didn't see that before, I should have searched more.

**Comment by defnull** [comment]
We need to find a good place to document this decision, so no more work is wasted on this topic. Sorry for the difficulty, @mfm24

**Comment by ghonchesefidi** [comment]
Hi guys
I had ran my server in https version but when I request for http version nothing happen.
In other word now that I have https version fine and running, how can I redirect it to https version?
I had seen [this plugin](https://pypi.org/project/Bottle-SSLify/) but I'm using python3.7 and its not working on this version.
Any help?

**Pull request closed without merging**
