### PR TITLE
Add Support for UVLoop and custom asyncio loop option

### PR DESCRIPTION
**Pull request by sideffect0**
* added custom asyncio loop ServerAdapter
* added UVLoop server option

### CODE REVIEW

**Comment by rcarmo** [comment]
I can confirm this works for me on Python 3.5.1 on LInux x64.

**Comment by sideffect0** [comment]
@rcarmo hope soon it will be updated to the main code base :)

**Comment by smakhtin** [comment]
I checked pull, looks clean. Hope it will be merged soon.

**Comment by sideffect0** [comment]
One of the feature i like in bottle is its insupport for other server implementations :+1:

**Pull request merged**
