### PR TITLE
bugfix: support multiple proxies ('HOSTNAME, HOSTNAME2' syntax)

### PR DESCRIPTION
**Pull request by danysirota**
take the first one in urlparts

### CODE REVIEW

**Comment by defnull** [comment]
HTTP/1.1 does not allow multiple hosts in a single `Host` header.
https://tools.ietf.org/html/rfc7230#section-5.4

**Comment by defnull** [comment]
Sorry, `X-Forwarded-For` does indeed support multiple hostnames.

**Comment by danysirota** [comment]
Hi,

Can you please merge the pull request?

Thanks

**Comment by JonathanHuot** [comment]
@danysirota, I think the PR should handle only `X-Forwarded-Host` and not when the `host` variable is built with `Host` or `SERVER_NAME`.

**Comment by defnull** [comment]
Please continue discussion in #1109

**Pull request closed without merging**
