### PR TITLE
Don't berate users about their lack of domain-specific knowledge.

### PR DESCRIPTION
**Pull request by colons**
It's [pretty discouraging](http://adamonishi.com/2015/02/obviously-language-in-education/) to be told you should have known something you don't know.

### CODE REVIEW

**Comment by vaultah** [comment]
Perhaps I'm not the one who should respond to you, but I can't see how the use of "of course" berates newbies.

**Comment by foxbunny** [comment]
@vaultah You're not the only one. Though the edits are all ok (they don't take away from the documentation, makes text flow a bit better, etc), the title of the PR is a bit over the top.

**Comment by avelino** [comment]
@foxbunny +1

**Comment by defnull** [comment]
Looks like I really like the term "of course" ;) Thanks for taking the time and rewording these parts.

**Pull request merged**
