### PR TITLE
Added `code` argument to static_file

### PR DESCRIPTION
**Pull request by SamuelMarks**
Sometimes I use `static_file` to return something I've created during a `POST`. There the `201` response code makes more sense.

### CODE REVIEW

**Comment by camconn** [comment]
This seems like an unneeded feature.

Why not just do the following? It uses an undocumented method, yet it still works out well. Because `static_file` just returns an `HTTPResponse` object, you can set the response status status manually.
    
```python
static_resp = static_file('some_file.txt', '/some/path')
static_resp._set_status(200)  # 200 can be any other status code
return static_resp
```

**Comment by eric-wieser** [comment]
@camconn: Or maybe avoid the "private" method, and use `static_resp.status = 200`

**Comment by avelino** [comment]
Default source:

    return HTTPResponse(body, **headers)

With this code you see this above just set a status header, example:

    response.set_header('status', 200)

**Comment by defnull** [comment]
Huh? Status is not a header.

**Comment by SamuelMarks** [comment]
Naturally I can modify the response and use the `.status` method, but what's the disadvantage in having it as an argument to `static_file`?

**Comment by eric-wieser** [comment]
> what's the disadvantage

Unpythonic?

`import this`:
* Special cases aren't special enough to break the rules.
* There should be one-- and preferably only one --obvious way to do it.

**Comment by defnull** [comment]
I am with @camconn and @eric-wieser here. `static_file()` returns a `HTTPResponse` that can be modified and changed just fine::

    def new_static_file(*a, **ka)
        res = static_file(*a, **ka)
        if res.status_code == 200:
            res.status = 201
        return res

**Pull request closed without merging**
